name: swali
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.12
  - biopython
  - mdtraj
  - scikit-learn
  - matplotlib
  - tqdm
  - seaborn
  - pip
  - pip:
      - torch
      - transformers
      - sentencepiece
      - protobuf
      - tmtools